name: "Next Change"
description: "Parse and update CHANGELOG.md"
author: "Vlad Emelianov"
inputs:
  path:
    description: Path to CHANGELOG.md
    default: "./CHANGELOG.md"
    required: false
  release:
    description: Get or create a release to edit, set it as target
    default: ""
    required: false
  clear:
    description: Delete everything from target release notes if it exists and not empty
    default: "false"
    required: false
  get:
    description: Replace target release notes with notes of release provided here, e.g. Undefined
    default: ""
    required: false
  set:
    description: Fully replace target release notes with parameter value
    default: ""
    required: false
  append:
    description: Append new lines to target release notes from parameter value
    default: ""
    required: false
  suffix:
    description: Add suffix to each section of append notes, good for pasting a link to PR
    default: ""
    required: false
  save:
    description: Whether to save changes back to CHANGELOG.md path
    default: "true"
    required: false
  sanitize:
    description: Keep only Keep a Changelog sections in target release notes
    default: "false"
    required: false
  encoding:
    description: Encoding for CHANGELOG.md
    default: "utf-8"
    required: false
outputs:
  result:
    description: Target Release notes
  titles:
    description: Comma-separated Keep a Changelog titles from release notes
  label:
    description: "Release label based on release notes: major, minor, or patch"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "list"
  color: "green"
